name: WhitelistByTime
main: ru.nightmirror.wlbytime.shared.WhitelistByTime
version: 3.2
author: NightMirror
description: Adding a player to the whitelist for a time
api-version: 1.16
commands:
  whitelist:
    usage: /whitelist help
  wl:
    usage: /wl help
permissions:
  whitelistbytime.add:
    default: op
  whitelistbytime.remove:
    default: op
  whitelistbytime.check:
    default: op
  whitelistbytime.reload:
    default: op
  whitelistbytime.getall:
    default: op
  whitelistbytime.time:
    default: op